sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kabulgrover/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kabulgrover/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-107348091944'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
